### ISSUE TITLE
Unclear examples

### ISSUE THREAD

**Issue by QuentinRoy** [beerose/simple-zustand-devtools#15]
Reading the documentation, I do not understand how to use the library.

The example shows:
```js
import create from 'zustand';
import { mountStoreDevtool } from 'simple-zustand-devtools';

export const useStore = create(set => {
  // create your zustand store here
});

if (process.env.NODE_ENV === 'development') {
  mountStoreDevtool('Store', store);
}
```

Where does `store` comes from? I have tried replacing `store` by `useStore`, but typescript complains.

**Comment by QuentinRoy** [comment]
Is there some special place we are supposed to write this? Is this supposed to be part of the store creator?

**Comment by goldenjayr** [comment]
I have the same issue.

**Comment by QuentinRoy** [comment]
@goldenjayr maybe try this instead: https://github.com/pmndrs/zustand#redux-devtools

**Comment by dkgrieshammer** [comment]
it's an error in the example, should be "useStore"

**Comment by goldenjayr** [comment]
Yup it worked. Yey. 

The zustand redux devtools doesn't work for me. My app gets laggy. but this one works. I actually prefer this :D. Thanks for this.

**Comment by beerose** [comment]
Hey, I'm sorry for the delay. I just updated the examples. Thanks for your patience!
