### ISSUE TITLE
Update to React 18

### ISSUE THREAD

**Issue by AvivAbachi** [beerose/simple-zustand-devtools#21]
### Dependencies
- `react@18.0.0-rc.0`
- `react-dom@18.0.0-rc.0`

### Error
**Console log:** "ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17."

**Comment by verekia** [comment]
The bug happens because of this `render` which needs to be changed to `createRoot`:

https://github.com/beerose/simple-zustand-devtools/blob/master/src/index.tsx#L51

https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis
