### ISSUE TITLE
NextJS ReferenceError: document is not defined

### ISSUE THREAD

**Issue by HodenKlaus** [beerose/simple-zustand-devtools#23]
![image](https://user-images.githubusercontent.com/19792468/163548091-a87a1f52-6ac1-4714-a11f-a9c117a33f9a.png)
Having some trouble with NextJS.

    "next": "^12.1.2",
    "simple-zustand-devtools": "^1.0.1",
    "zustand": "^3.7.2"
    "react": "^17.0.2",

**Comment by ZMonk91** [comment]
This has to do with the way Next.JS renders everything. 

The solution is here: # https://stackoverflow.com/questions/69386843/nextjs-referrenceerror-document-is-not-defined

**Comment by beerose** [comment]
Thanks for reporting and sorry for the delay! Fixed in https://github.com/beerose/simple-zustand-devtools/commit/57531813902a0df4a31d5ead022b114f4cbd1435
