### ISSUE TITLE
Wrong version for old react

### ISSUE THREAD

**Issue by phazzzy** [beerose/simple-zustand-devtools#28]
Hi!

The installation instructions say to use version 1.0.2 for react 17, but react 18 in the dependencies list.

![ceZ3GLc47W](https://user-images.githubusercontent.com/26648228/183289360-b65a04b2-8794-4c23-9243-d520526c7e87.png)

**Comment by kahboom** [comment]
Yeah my team needs to stay on React 17.x, so I tried to install the legacy deps (using Yarn), but I'm still getting the following:

```
ERROR in ./node_modules/simple-zustand-devtools/dist/simple-zustand-devtools.es.production.js 1:49-95
Module not found: Error: Can't resolve 'react-dom/client' in '~/project/node_modules/simple-zustand-devtools/dist'
```

**Comment by phazzzy** [comment]
![image](https://user-images.githubusercontent.com/26648228/187221881-2379bd20-84e2-434e-a5cb-b04e030905b1.png)
this works for me, @kahboom

**Comment by beerose** [comment]
The information in the readme is wrong — should say to install 1.0.1 (instead of 1.0.2). Sorry about that — fixing it now.

**Comment by phazzzy** [comment]
Thanks for the fix, but I need more fixes! :D

in the installation code is corrected, but in the text is not

![image](https://user-images.githubusercontent.com/26648228/211614018-ae7514da-ae19-4476-8c8d-7280182b3b06.png)

**Comment by beerose** [comment]
Ah yeah, I left it because I assumed that word "prior" indicates that it has to be lower than 1.0.2 😅 Will correct it to avoid any confusion
